python research_code/train.py --exp_name instance_unet_cloud_shadow --train_df train_val_df.csv --network instance_unet --batch_size 16 --input_width 256 --input_height 256 --epochs 30 --class_names cloud_shadow --manual_dataset_dir dataset/train/ --test_data_dir dataset/val/ &&
python research_code/train.py --exp_name instance_unet_double_plant --train_df train_val_df.csv --network instance_unet --batch_size 16 --input_width 256 --input_height 256 --epochs 30 --class_names double_plant --manual_dataset_dir dataset/train/ --test_data_dir dataset/val/ &&
python research_code/train.py --exp_name instance_unet_planter_skip --train_df train_val_df.csv --network instance_unet --batch_size 16 --input_width 256 --input_height 256 --epochs 30 --class_names planter_skip --manual_dataset_dir dataset/train/ --test_data_dir dataset/val/ &&
python research_code/train.py --exp_name instance_unet_standing_water --train_df train_val_df.csv --network instance_unet --batch_size 16 --input_width 256 --input_height 256 --epochs 30 --class_names standing_water --manual_dataset_dir dataset/train/ --test_data_dir dataset/val/ &&
python research_code/train.py --exp_name instance_unet_waterway --train_df train_val_df.csv --network instance_unet --batch_size 16 --input_width 256 --input_height 256 --epochs 30 --class_names waterway --manual_dataset_dir dataset/train/ --test_data_dir dataset/val/ &&
python research_code/train.py --exp_name instance_unet_weed_cluster --train_df train_val_df.csv --network instance_unet --batch_size 16 --input_width 256 --input_height 256 --epochs 30 --class_names weed_cluster --manual_dataset_dir dataset/train/ --test_data_dir dataset/val/

python research_code/train.py --exp_name instance_unet_cloud_shadow_augmented --train_df train_val_df.csv --network instance_unet --batch_size 16 --input_width 256 --input_height 256 --epochs 30 --class_names cloud_shadow --manual_dataset_dir dataset/train/ --test_data_dir dataset/val/ --use_aug &&
python research_code/train.py --exp_name instance_unet_double_plant_augmented --train_df train_val_df.csv --network instance_unet --batch_size 16 --input_width 256 --input_height 256 --epochs 30 --class_names double_plant --manual_dataset_dir dataset/train/ --test_data_dir dataset/val/ --use_aug &&
python research_code/train.py --exp_name instance_unet_planter_skip_augmented --train_df train_val_df.csv --network instance_unet --batch_size 16 --input_width 256 --input_height 256 --epochs 30 --class_names planter_skip --manual_dataset_dir dataset/train/ --test_data_dir dataset/val/ --use_aug &&
python research_code/train.py --exp_name instance_unet_standing_water_augmented --train_df train_val_df.csv --network instance_unet --batch_size 16 --input_width 256 --input_height 256 --epochs 30 --class_names standing_water --manual_dataset_dir dataset/train/ --test_data_dir dataset/val/ --use_aug &&
python research_code/train.py --exp_name instance_unet_waterway_augmented --train_df train_val_df.csv --network instance_unet --batch_size 16 --input_width 256 --input_height 256 --epochs 30 --class_names waterway --manual_dataset_dir dataset/train/ --test_data_dir dataset/val/ --use_aug &&
python research_code/train.py --exp_name instance_unet_weed_cluster_augmented --train_df train_val_df.csv --network instance_unet --batch_size 16 --input_width 256 --input_height 256 --epochs 30 --class_names weed_cluster --manual_dataset_dir dataset/train/ --test_data_dir dataset/val/ --use_aug